spring:
  profiles:
    default: local

  # 메일 설정
  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(aODbNtapT7RBuM27QkCDHdgyJORPto7A)
    password: ENC(ndCavilUFaDNSC/aBDyJlcdL3ySgdOmy)
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

  # oauth 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(uTmUe3/W8In1+WmDVIAiQ/5+5Y7Oy6pRm43pytRe8p/8TfxHFP53G9EJHr9QXOvXF0nydbr56ahnvg+wShMFOMqSKtcMJ6eUzmrsBZSE9aSTRW7x7BXNnw==)
            client-secret: ENC(vKSRL4Hllw5KpnS5EmrgcRsGweaSIHVwLQUHEceCcq7wFMAW9GIjmKEL9tZ/3YUI)
            scope:
              - openid
              - profile
              - email
          kakao:
            client-id: ENC(n4OSe67MumM65r8zdpky0BlZp3uX9rGq9DRVcW3P1DxGi341wC3bD0vgsikha15g)
            client-secret: ENC(T0Yr9hUwmv8aKLZU5yTbh3GrbA8B99cEkcChZf5EG4cMPEFRiyxdq0C3f/srZ3a4)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: blog
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - openid
              - profile_nickname
              - profile_image
              - account_email
            provider: kakao
          naver:
            client-id: ENC(6bHb92tALlxA2hakSI16YUuUk6YkqVYWCy+I5ZbQH7w=)
            client-secret: ENC(SyBYigPQI1A0WE3owWCjbYoKrufhQxOU)
            client-name: blog
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            provider: naver

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  thymeleaf:
    cache: false

  # 레디스 설정
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 100

server:
  servlet:
    session:
      timeout: 1800
  error:
    whitelabel:
      enabled: false

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

logging:
  level:
    org:
      springframework.cache: trace
      hibernate:
        orm:
          jdbc:
            bind: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    operations-sorter: alpha
    tags-sorter: alpha
    enabled: true
  enable-spring-security: true
  show-login-endpoint: true
  default-support-form-data: true

coolsms:
  apiKey: ENC(v1jvmgKPcv63UJXsl+ybJ/DwBT09Cau9bi7n2KbkOoA=)
  secretKey: ENC(QGTqNLt/LFyHXtYCYmm9oPysZGOkeOIbFML6MieOKqp6dPdwsF6F9BOUVohIWUgd)
  from: ENC(hVxmAVUhFdZP6I6r+RKMN7XbDHWaszOs)

kakao:
  logout:
    uri: https://kauth.kakao.com/oauth/logout
    client-id: ENC(n4OSe67MumM65r8zdpky0BlZp3uX9rGq9DRVcW3P1DxGi341wC3bD0vgsikha15g)
    redirect-uri: http://localhost:8080/login

# aws s3 설정
cloud:
  aws:
    s3:
      bucket: geunblog
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(Ygyco5iE1GZwrh4jbrYSBivHC8mYkfs7Su3CaKHkLik=)
      secret-key: ENC(iA76vtakKr36GXZjbAgzilVxI7K2SBPuQt4//AjHlyz6Yau5V+R20s3DS6Pzb9o/JY/Pnv9+S4A=)

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/blog?rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQLDialect

profile:
  default:
    image-url: https://geunblog.s3.ap-northeast-2.amazonaws.com/user/default-user-image.jpg

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.transaction.interceptor: debug
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

file:
  dir: C:/Users/User/Desktop/blog/upload