spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://geuns-blog.com/login/oauth2/code/kakao
          naver:
            redirect-uri: https://geuns-blog.com/login/oauth2/code/naver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

profile:
  default:
    image-url: ${DEFAULT_IMAGE_URL}