spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_URI}
          naver:
            redirect-uri: ${NAVER_REDIRECT_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# aws s3 설정
cloud:
  aws:
    s3:
      bucket: geunblog
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(Ygyco5iE1GZwrh4jbrYSBivHC8mYkfs7Su3CaKHkLik=)
      secret-key: ENC(iA76vtakKr36GXZjbAgzilVxI7K2SBPuQt4//AjHlyz6Yau5V+R20s3DS6Pzb9o/JY/Pnv9+S4A=)

profile:
  default:
    image-url: ${DEFAULT_IMAGE_URL}