spring:
  config:
    activate:
      on-profile: local
    import: application-aws.yml

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none