spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
    username: sa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
  h2:
    console:
      enabled: true