spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.transaction.interceptor: debug
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

file:
  dir: C:/Users/User/Desktop/blog/upload