spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(uTmUe3/W8In1+WmDVIAiQ/5+5Y7Oy6pRm43pytRe8p/8TfxHFP53G9EJHr9QXOvXF0nydbr56ahnvg+wShMFOMqSKtcMJ6eUzmrsBZSE9aSTRW7x7BXNnw==)
            client-secret: ENC(vKSRL4Hllw5KpnS5EmrgcRsGweaSIHVwLQUHEceCcq7wFMAW9GIjmKEL9tZ/3YUI)
            scope:
              - openid
              - email

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후 sql 파일 실행
    defer-datasource-initialization: true

jwt:
  issuer: ENC(XD3KNuRKbcq1POQl4lo2f98SxP4HylXrUDTNeBR1G7U=)
  secret_key: ENC(s8+oCX5whHJv6Xozto5BaHJVHM6EmHy4IEfnqCNyzqC+co8RA+thrQha+aE2/u+kw8tarCvg/JNv824g+YxUUJpOHGIhiYWHccGLZtrJjqoyEh7Kj6431HD/Lx+OqNzuLcI9x7AtQH7h1zpVce2gyjHQBdvwnYbafhy/eCSycomxj0zeTn8FOSu/8FMo2PKI)

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}
