spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://geuns-blog.com/login/oauth2/code/kakao
          naver:
            redirect-uri: https://geuns-blog.com/login/oauth2/code/naver

  data:
    redis:
      host:
      port: